### ISSUE TITLE
Add support for custom post types

### ISSUE THREAD

**Issue by viktorix** [azurecurve/azrcrv-markdown#2]
Would it be possible to add support for custom post types? I'm migrating a website from WordPress.com, which was using custom post types for Portfolio and it uses Markdown in the content. 

Maybe making the settings page dynamic, so it checks for all registered post types and allows enabling it for each one. Using something like `get_post_types()` to get all registered ones.

**Comment by azurecurve** [comment]
Yes, I should have time to take a look at this next week.

**Comment by azurecurve** [comment]
I've done some additional testing and I think this would only make sense to do for public custom post types?

**Comment by azurecurve** [comment]
v3 has been released with this functionality.

**Comment by viktorix** [comment]
Hi, sorry I didn't get to reply in time. Limiting it to public CPTs is the right choice. Thanks for taking the time to work on this.

**Comment by azurecurve** [comment]
Thanks for confirming I made the right call on CPT.
